### ISSUE TITLE
pixel2map pole test seg faults on mac

### ISSUE THREAD

**Issue by SgStapleton** [DOI-USGS/ISIS3#3183]
The pixel2map_app_test_pole test has been failing for prog27. I could not tie this to any code changes (I believe this started sometimes over the shutdown). This should be investigated before the isis3.7.0-RC goes out.

**Comment by jessemapel** [comment]
This does not fail on my macbook :/

**Comment by SgStapleton** [comment]
I was thinking this was going to be the case. :-(   (In fact, I think I may remember having you check that before...?) I am wondering if the new imaging of prog27 will fix this. As soon as I can get on there I will check this.

**Comment by jlaura** [comment]
Can we test on prog26 - the new prog27...

**Comment by SgStapleton** [comment]
Wait, prog26 IS the new prog27? I am confused!

**Comment by SgStapleton** [comment]
I am able to reproduce this on the new prog26 setup. I am seeing the error:
```
pixel2map(59987,0x7fff95bb8380) malloc: *** error for object 0x7f87cd547b18: pointer being freed was not allocated
```

I am a little confused how this is happening on prog26, but not on @jessemapel 's machine. There is no DDT installed on prog26, but I will run this in debugger as soon as I can.

**Comment by jessemapel** [comment]
@SgStapleton I'm confused why this is happening on prog26 but not any of the other machines.

**Comment by jessemapel** [comment]
I think this is an issue with the environment being used. Using my local dev environment it's fine. Using the nightly build environment it breaks. Going to update the nightly build environment.

**Comment by jessemapel** [comment]
There's a chance this is going to break existing builds :((((( I don't think anyone is using the mac pkgs builds though.

**Comment by jessemapel** [comment]
Updating the environment did not fix this

**Comment by jlaura** [comment]
Just to summarize: we have 2 identical environments on the same OSX version, but different hardware and we are getting a malloc error out of somewhere?

**Comment by jessemapel** [comment]
@jlaura Even if I build and test on the same system with different environments we get 2 different results. With a fresh local anaconda environment on my laptop it passes. If I switch to a fresh NFS anaconda environment using my laptop it fails.

**Comment by jlaura** [comment]
But what conda are you using? For your laptop it is your local (only) base. When you create that env on the NFS installation, are you using the NFS base?

**Comment by jessemapel** [comment]
@jlaura I created an environment on the NFS drive with isis3mgr and then activated it by adding the NFS environments to by local anaconda environments and built.

**Comment by jessemapel** [comment]
Okay, latest new is this is not related to where your anaconda is installed, it is caused by an update to our third party libraries. I'm not sure which though, looking into it.

**Comment by jessemapel** [comment]
Good news! Installing `libcxx` fixed the problem. I had to use a wonky command because conda-forge has everything flagged as broken for some reason but `conda install -c conda-forge/label/broken libcxx` worked. Going to try running all of the tests now.

**Comment by jessemapel** [comment]
So the solution for this is to get conda-forge to either fix their builds if they are actually all broken, or have them unflag them as broken. For right now, if we manually update the prog26 dev environment it will be okay. I'm hoping to get more info from the [conda-forge folks](https://github.com/conda-forge/libcxx-feedstock/issues/35)

**Comment by SgStapleton** [comment]
Confirmed this test is now passing. The nightly builds are somehow still using the old version of anaconda, but I updated that environment as well, so this should be fixed with tonight's build.

**Comment by jessemapel** [comment]
Fixed in the 4/1 nightly build. I'm going to close this and continue to try and get conda-forge to update their tarballs

**Comment by SgStapleton** [comment]
While getting the release candidate out the door, it was discovered how difficult it was to have conda-build pull the right version of libcxx for this fix. It was decided to continue the build without it, therefor the 3.7.0-RC will still have this bug. We may need to open an issue to actually fix this is-code.

**Comment by jessemapel** [comment]
@SgStapleton I think the proper fix for this is to get conda-forge to serve cxx under it's main label.

**Comment by jessemapel** [comment]
conda-forge has fixed this. Their 7.0 build for OSX was broken, but the 6.0 build is good and is now properly pulled when installing the environment.

**Comment by SgStapleton** [comment]
One quick question: It was explained to me that this was caused by a mismatch in allocation and deallocation (somewhere in our code, we are using a c-style allocation with a c++ style destruction, or vise-versa) that older versions of libcxx do not know how to handle. If we were to fix this in-code, we would theoretically not be needing to pull any particular version of libcxx via conda (making a new dependency), but could use whatever version was installed on the systems? Or am I misunderstanding this?
